// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-solar-estimate.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var get_solar_estimate_default = defineTool({
  name: "get_solar_estimate",
  title: "Get solar estimate",
  description: "Estimate a Calgary/Alberta solar PV system: recommended size, annual production, savings (standard vs Solar Club retailer), turn-key cost, payback, CO\u2082 avoided, and CEIP financing. Returns engineering baseline plus an AI-written recommendation.",
  inputSchema: {
    monthlyBill: z.number().positive().describe("Monthly electricity bill in CAD."),
    propertyType: z.enum(["residential", "commercial", "agricultural", "multi-family"]).describe("Property type."),
    roofOrientation: z.enum(["south", "south-east", "south-west", "east-west", "north"]).describe("Primary roof orientation."),
    roofSize: z.number().nonnegative().describe("Available roof area in m\xB2 (0 if unknown)."),
    hasEV: z.boolean().default(false).describe("Electric vehicle in the household."),
    hasBattery: z.boolean().default(false).describe("Wants battery storage."),
    postalCode: z.string().optional().describe("Canadian postal code (optional).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (input) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !anon) {
      return { content: [{ type: "text", text: "Server not configured." }], isError: true };
    }
    const res = await fetch(`${url}/functions/v1/solar-analysis`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${anon}`,
        apikey: anon
      },
      body: JSON.stringify(input)
    });
    const data = await res.json();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Solar analysis failed: ${JSON.stringify(data)}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/join-waitlist.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var join_waitlist_default = defineTool2({
  name: "join_waitlist",
  title: "Join Nullpunkt waitlist",
  description: "Register a Calgary/Alberta homeowner or business on the Nullpunkt Energy waitlist for a solar consultation. Sends confirmation and internal notification emails.",
  inputSchema: {
    name: z2.string().min(1).max(100).describe("Full name of the contact."),
    email: z2.string().email().describe("Contact email address."),
    postal_code: z2.string().max(10).optional().describe("Canadian postal code."),
    property_type: z2.string().max(50).optional().describe("e.g. residential, commercial, agricultural."),
    monthly_bill: z2.number().nonnegative().optional().describe("Monthly electricity bill in CAD."),
    notes: z2.string().max(500).optional().describe("Free-form notes from the user.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !anon) {
      return { content: [{ type: "text", text: "Server not configured." }], isError: true };
    }
    const res = await fetch(`${url}/functions/v1/join-waitlist`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${anon}`,
        apikey: anon
      },
      body: JSON.stringify({ ...input, source: "mcp" })
    });
    const data = await res.json();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Waitlist signup failed: ${JSON.stringify(data)}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `Signed up ${input.name} (${input.email}). Confirmation email sent.` }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-services-overview.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_services_overview_default = defineTool3({
  name: "get_services_overview",
  title: "Get Nullpunkt services overview",
  description: "Return a structured overview of Nullpunkt Energy's core services, target market (Calgary / Alberta), pricing posture, and contact channels.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const overview = {
      company: "Nullpunkt Energy (Calgary subsidiary of SMB Solartechnik GmbH)",
      slogan: "German Precision \u2014 Zero Emissions",
      market: "Calgary and greater Alberta, Canada",
      services: [
        {
          name: "Turn-key residential solar PV",
          description: "Engineering, permits, install, commissioning and HEMS for single-family and multi-family homes. Typical 4\u201320 kWp systems, Class 3+ hail-rated panels, 30\xB0+ tilt for winter snow shedding."
        },
        {
          name: "Commercial & agricultural solar",
          description: "150 kW\u20135 MW systems settled hourly under Alberta's Micro-Generation Regulation. Eligible for the 30% Clean Technology ITC."
        },
        {
          name: "Battery storage (LFP)",
          description: "5\u201320 kWh installed alongside PV or as retrofit; ~CAD $800/kWh turn-key."
        },
        {
          name: "Solar analysis & site design",
          description: "Free consultation, site visit, and engineering-led proposal comparing standard vs Solar Club retailer scenarios and CEIP financing."
        }
      ],
      pricing: {
        pvTurnkeyPerKwp: "CAD ~$2,100/kWp (all-in)",
        batteryPerKwh: "CAD ~$800/kWh installed",
        note: "Low end of Alberta market via direct EU supplier through SMB Solartechnik."
      },
      programs: ["Alberta Micro-Generation Regulation", "Solar Club (UTILITYnet)", "CEIP (PACE financing)", "Clean Technology ITC (30%, commercial)"],
      contact: {
        email: "hello@nullpunkt.ca",
        phone: "+1 (403) 819-7834",
        website: "https://nullpunkt.ca"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: overview
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/data/blogPosts.ts
import calgaryIncentivesImg from "npm:@/assets/blog-calgary-incentives.jpg";
import sustainableArchImg from "npm:@/assets/blog-sustainable-architecture.jpg";
import minimalistLivingImg from "npm:@/assets/blog-minimalist-living.jpg";
import urbanPlanningImg from "npm:@/assets/blog-urban-planning.jpg";
var blogPosts = [
  {
    id: "calgary-solar-incentives-2026",
    title: "Calgary Solar Incentives 2026: A Homeowner's Guide",
    excerpt: "What rebates, loans and net-billing programs actually pay out for a Calgary home solar system in 2026 \u2014 plus the small print most installers skip.",
    content: `
# Calgary Solar Incentives 2026: A Homeowner's Guide

Going solar in Calgary is no longer an experimental decision. The hardware has matured, electricity prices have stabilised at a new, higher baseline, and three layers of public programs now stack on top of each other to shorten the payback window. This guide walks through what is actually available in 2026, who qualifies, and the engineering details that decide whether you receive the full benefit or leave money on the table.

> **Disclaimer:** Program terms change. Always confirm current eligibility with the City of Calgary, Natural Resources Canada and your retailer before signing a contract. The numbers below reflect publicly available program documentation at the time of writing.

## 1. The Two Layers You Can Stack

A well-designed Calgary residential project in 2026 typically combines:

1. **Municipal financing** \u2014 the City of Calgary's Clean Energy Improvement Program (CEIP), repaid through your property tax bill.
2. **Provincial net billing** \u2014 Alberta's Micro-Generation Regulation, which lets your retailer credit you for the electricity you export.

The federal Canada Greener Homes *Grant* closed in early 2024, and the interest-free *Loan* program has since stopped accepting new applications as well. There is no active federal cash incentive for residential solar in 2026 \u2014 which makes the municipal and provincial layers more important than ever.

> **Heads-up:** Some installers still advertise "Greener Homes" financing in their marketing. Ask explicitly whether your application would actually be funded, or whether the program is just being used as a sales hook.

## 2. City of Calgary CEIP (Clean Energy Improvement Program)

CEIP is Calgary's local financing tool. It is technically a form of PACE (Property Assessed Clean Energy) financing: the City lends the money, and you repay it as a line item on your annual property tax bill.

- **Tied to the property, not the person.** If you sell the home, the remaining balance can transfer to the new owner (subject to lender consent).
- **Repayment term:** Up to 20 years for solar and major envelope upgrades.
- **Rate:** Fixed for the full term, set when the program window opens \u2014 historically competitive with prime.
- **Eligible measures:** Solar PV, battery storage, geothermal, deep envelope retrofits.

For most Calgary homeowners, CEIP is now the primary public-financing route \u2014 it can cover the full project, including a Powerwall-class battery, with no upfront cash.

**Technical note:** CEIP runs in defined intake windows. Plan your project around the published application calendar rather than the other way around. An EnerGuide-style energy assessment is part of the qualification process.

## 3. Alberta Micro-Generation Regulation (Net Billing)

This is the provincial framework that allows your meter to spin in both directions. Two things matter for homeowners:

- **Eligible system size:** Up to 5 MW, far beyond any residential need. Practically, your system is sized to your annual consumption.
- **Credit value:** You are credited at your retailer's energy rate (not the full delivered cost). The exact number depends on which retailer you are with \u2014 Enmax, Direct Energy and the various competitive retailers all publish slightly different micro-gen rates.

**Homeowner takeaway:** Pick your retailer deliberately. The difference between the best and worst micro-gen rate in Alberta can shift your payback by 12-18 months on a typical 10 kW system.

**Technical note:** Credits are applied energy-for-energy in cents, but you still pay distribution and transmission charges on imported kWh. A battery improves the economics by raising your self-consumption ratio \u2014 typically from ~30% (PV only) to 65-80% (PV + battery + smart control) on a south-facing Calgary roof.

## 5. The Hidden Variables That Decide Your Payback

Two homes on the same street, with the same array size, can have payback periods two years apart. The differences usually come down to:

### Roof orientation and pitch
Calgary's optimal tilt for annual yield sits around 45\xB0. South-facing is best, but east/west splits perform surprisingly well in summer \u2014 and matter more if you have a battery, because you flatten the production curve.

### Inverter and string design
A poorly zoned string inverter on a partially shaded roof can lose 15-20% of annual yield. Microinverters or DC optimisers cost more upfront but recover the difference within a few years on most Calgary roofs, which tend to have at least one chimney, vent stack or tree edge causing partial shading.

### Snow management
Calgary winters are sunny but snowy. Module tilt, frame height and the dark-glass thermal effect all influence how quickly snow sheds. A 40\xB0+ tilt sheds passively within hours of sunrise on a clear day; a 15\xB0 tilt on a low-slope roof may sit under snow for days.

### Battery dispatch logic
A battery is only as good as the software running it. A well-tuned Home Energy Management System (HEMS) prioritises self-consumption when export credits are low and exports aggressively during peak retail hours when they are high. This is where the parent-company OpenEMS stack we bring from Germany pays off \u2014 it is rules-based, transparent and tunable, not a black box.

## 6. A Realistic Calgary Example

A 10.4 kW rooftop array with a 13.5 kWh battery on a south-facing, 35\xB0-pitch roof in Calgary, designed with proper string layout and HEMS control:

- **System cost:** roughly $38,000 - $45,000 installed, depending on roof complexity and battery brand.
- **Annual yield:** ~12,500 kWh.
- **Self-consumption with battery + HEMS:** 70-80%.
- **Combined annual benefit (avoided imports + export credits):** $2,200 - $2,800 at current Alberta rates.
- **Financing:** CEIP can cover the full project amount, repaid through the property tax bill over up to 20 years.
- **Net cash-flow position:** Positive from year one in most scenarios; full payback in 9-12 years; 25-year linear-warranty modules continue producing well beyond that.

## 7. How to Approach Your Project

1. **Start with consumption data.** Pull 12 months of hourly data from your retailer before any installer designs an array.
2. **Check the next CEIP intake window early.** It is the gatekeeper for municipal financing and has fixed application dates.
3. **Get an engineered proposal, not a sales quote.** A real proposal includes a yield simulation, a single-line diagram, a bill-of-materials, and a payback model. If you do not see those, you are looking at a sales sheet.
4. **Choose your retailer with the micro-gen rate in mind.** Switching retailers is a five-minute task with multi-year financial consequences.
5. **Design for the battery you may add later**, even if you start with PV only. Cable sizing, inverter choice and panel position all matter.

---

If you would like a no-pressure review of your roof and your last 12 months of consumption against the current programs, that is exactly the conversation we are set up to have. We will tell you when the numbers do not work \u2014 and walk away \u2014 just as readily as when they do.
    `,
    author: "NullPunkt Engineering",
    date: "2026-06-23",
    readTime: "9 min read",
    category: "INCENTIVES",
    image: calgaryIncentivesImg
  },
  {
    id: "sustainable-architecture-future",
    title: "The Future of Sustainable Architecture",
    excerpt: "Exploring how modern architectural practices are evolving to meet environmental challenges while maintaining design excellence.",
    content: `
# The Future of Sustainable Architecture

The architectural landscape is undergoing a profound transformation as we face the urgent need to address climate change and environmental degradation. Sustainable architecture is no longer a niche consideration\u2014it has become the cornerstone of responsible design practice.

## Defining Sustainable Architecture

Sustainable architecture encompasses more than just energy efficiency. It represents a holistic approach to building design that considers the entire lifecycle of a structure, from material sourcing to end-of-life disposal. This philosophy integrates environmental, social, and economic factors to create buildings that not only minimize their ecological footprint but also enhance the quality of life for their occupants.

## Key Principles of Sustainable Design

### Material Selection
The choice of building materials plays a crucial role in sustainable architecture. Architects are increasingly turning to:
- Recycled and upcycled materials
- Locally sourced materials to reduce transportation emissions
- Bio-based materials like bamboo, cork, and mycelium
- Materials with low embodied energy

### Energy Efficiency
Modern sustainable buildings incorporate:
- Passive solar design principles
- High-performance insulation systems
- Smart building technologies
- Renewable energy integration
- Natural ventilation strategies

### Water Management
Sustainable architecture addresses water conservation through:
- Rainwater harvesting systems
- Greywater recycling
- Permeable landscaping
- Low-flow fixtures and appliances

## Emerging Trends

The future of sustainable architecture is being shaped by several emerging trends:

### Biophilic Design
The integration of natural elements into built environments is gaining momentum. This approach recognizes the innate human connection to nature and seeks to incorporate natural light, ventilation, vegetation, and organic forms into architectural design.

### Circular Economy Principles
Architects are beginning to design for disassembly, creating buildings that can be easily deconstructed and their materials reused in new projects. This approach challenges the traditional linear model of construction and waste.

### Carbon-Neutral and Carbon-Negative Buildings
The next generation of sustainable buildings aims not just to minimize carbon emissions but to actively remove carbon from the atmosphere through innovative design and material choices.

## Challenges and Opportunities

While the path toward sustainable architecture presents challenges\u2014including higher upfront costs, regulatory barriers, and the need for specialized knowledge\u2014it also offers tremendous opportunities. These include reduced operational costs, improved occupant health and productivity, and the potential to create resilient communities that can adapt to changing environmental conditions.

## Conclusion

The future of architecture lies in our ability to create buildings that work in harmony with natural systems. As architects, we have the responsibility and the opportunity to design a built environment that supports both human well-being and planetary health. The transition to sustainable architecture is not just an environmental imperative\u2014it is a creative challenge that will define the next era of architectural innovation.
    `,
    author: "Sarah Chen",
    date: "2024-03-15",
    readTime: "8 min read",
    category: "SUSTAINABILITY",
    image: sustainableArchImg
  },
  {
    id: "minimalism-modern-living",
    title: "Minimalism in Modern Living Spaces",
    excerpt: "How the principles of minimalist design are reshaping contemporary residential architecture and interior spaces.",
    content: `
# Minimalism in Modern Living Spaces

In an era of overwhelming digital noise and material excess, minimalist architecture offers a sanctuary of calm and clarity. This design philosophy, rooted in the Japanese concept of "ma" (negative space) and Scandinavian functionality, has evolved into a defining characteristic of contemporary residential design.

## The Philosophy Behind Minimalism

Minimalist architecture is not about creating empty or stark spaces\u2014it's about intentional design choices that prioritize function, beauty, and the essential elements of living. The approach emphasizes:

- **Simplicity over complexity**
- **Quality over quantity**
- **Space over stuff**
- **Light over ornament**

## Core Elements of Minimalist Design

### Clean Lines and Geometric Forms
Minimalist architecture favors simple geometric shapes and clean lines. This creates a sense of order and tranquility that serves as a backdrop for daily life. The absence of decorative elements allows the architecture itself to become the focal point.

### Natural Materials
The minimalist palette typically includes:
- Raw concrete
- Natural wood
- Steel and glass
- Stone and marble
- Neutral textiles

These materials are chosen for their inherent beauty and authenticity, often displayed in their natural state without excessive finishing or treatment.

### Strategic Use of Light
Natural light becomes a design element in minimalist spaces. Large windows, skylights, and glass walls not only illuminate the interior but create a connection with the outdoors. The interplay of light and shadow throughout the day adds depth and interest to otherwise simple surfaces.

### Functional Furniture and Built-ins
Every piece serves a purpose in minimalist design. Furniture is often built-in or carefully selected for both function and aesthetic value. Storage solutions are integrated seamlessly into the architecture, maintaining the clean lines while providing necessary functionality.

## The Psychology of Minimalist Living

Research in environmental psychology suggests that minimalist spaces can have profound effects on mental well-being:

### Reduced Stress and Anxiety
Clutter-free environments have been shown to reduce cortisol levels and promote feelings of calm and control.

### Enhanced Focus and Productivity
With fewer visual distractions, occupants often report improved concentration and mental clarity.

### Greater Appreciation for Quality
When surrounded by fewer but higher-quality items, people tend to develop a deeper appreciation for craftsmanship and design.

## Challenges and Considerations

### Storage Solutions
One of the biggest challenges in minimalist design is providing adequate storage while maintaining clean aesthetics. This requires creative solutions such as:
- Hidden storage compartments
- Multi-functional furniture
- Dedicated storage rooms or areas

### Personalization
Creating minimalist spaces that feel warm and personal requires careful curation of meaningful objects and artwork.

### Maintenance
Minimalist spaces can show wear and dirt more easily, requiring consistent maintenance to preserve their pristine appearance.

## Minimalism and Sustainability

The minimalist approach aligns naturally with sustainable design principles:
- **Reduced material consumption**
- **Focus on durability over trends**
- **Energy efficiency through passive design**
- **Long-term thinking over short-term aesthetics**

## Conclusion

Minimalism in modern living spaces represents more than just an aesthetic choice\u2014it's a lifestyle philosophy that prioritizes intention, quality, and well-being. As our lives become increasingly complex, the simplicity and clarity of minimalist design offer a path toward more meaningful and sustainable ways of living.

The challenge for architects and designers is to create minimalist spaces that feel alive and welcoming rather than cold or sterile. When executed thoughtfully, minimalist design can provide the perfect canvas for life's most important moments.
    `,
    author: "Marcus Rodriguez",
    date: "2024-03-10",
    readTime: "6 min read",
    category: "DESIGN",
    image: minimalistLivingImg
  },
  {
    id: "urban-planning-community-spaces",
    title: "Urban Planning and Community Spaces",
    excerpt: "Examining the role of thoughtful urban planning in creating vibrant, inclusive communities through architectural design.",
    content: `
# Urban Planning and Community Spaces

The fabric of our cities is woven through the careful orchestration of public and private spaces, each contributing to the complex ecosystem of urban life. As populations continue to urbanize, the role of thoughtful urban planning and community-centered architectural design becomes increasingly critical in shaping livable, sustainable, and equitable cities.

## The Evolution of Urban Planning

Urban planning has evolved from purely functional considerations\u2014managing traffic flow, utilities, and zoning\u2014to encompass broader goals of social equity, environmental sustainability, and community well-being. This shift recognizes that cities are not just collections of buildings and infrastructure, but complex social organisms that require careful nurturing.

### From Zoning to Place-Making

Traditional zoning practices often created segregated, single-use districts that required extensive commuting and limited social interaction. Contemporary urban planning embraces mixed-use development and place-making strategies that:

- **Encourage walkability and cycling**
- **Mix residential, commercial, and office spaces**
- **Create destinations rather than just developments**
- **Foster chance encounters and community building**

## The Architecture of Community

Community spaces serve as the living rooms of our cities\u2014places where strangers become neighbors, where cultural exchange happens naturally, and where the social fabric of urban life is strengthened.

### Public Squares and Plazas
Well-designed public squares act as outdoor rooms that can accommodate a variety of activities:
- **Markets and festivals**
- **Informal gatherings and people-watching**
- **Children's play and elderly socialization**
- **Political demonstrations and civic engagement**

### Community Centers and Libraries
Modern community centers are evolving beyond their traditional roles to become:
- **Flexible spaces that adapt to different needs**
- **Technology hubs providing digital access**
- **Venues for lifelong learning and skill development**
- **Safe havens during emergencies or extreme weather**

### Parks and Green Spaces
Urban parks provide essential ecosystem services while creating opportunities for recreation, contemplation, and community gathering. Effective park design considers:
- **Diverse programming for different age groups**
- **Seasonal activities and year-round usability**
- **Biodiversity and habitat creation**
- **Stormwater management and climate resilience**

## Principles of Inclusive Design

Creating truly community-centered spaces requires attention to inclusivity and accessibility:

### Universal Design
Spaces should be usable by people of all abilities, ages, and backgrounds. This includes:
- **Physical accessibility through ramps, elevators, and clear sightlines**
- **Sensory considerations for those with hearing or visual impairments**
- **Cultural sensitivity in programming and design**
- **Economic accessibility through free or low-cost activities**

### Safety and Comfort
Community spaces must feel safe and welcoming to all users:
- **Good lighting and clear sightlines**
- **Natural surveillance through strategic positioning**
- **Comfortable seating and weather protection**
- **Clean and well-maintained facilities**

## The Role of Participation

Successful community spaces are designed with, not just for, the people who will use them. Participatory design processes involve:

### Community Engagement
- **Public meetings and design charrettes**
- **Surveys and focus groups with diverse stakeholders**
- **Pop-up installations to test design ideas**
- **Ongoing feedback and adaptation**

### Cultural Responsiveness
Understanding the specific cultural context of a community is essential:
- **Recognizing existing social patterns and traditions**
- **Incorporating local materials and architectural vernacular**
- **Supporting local businesses and economies**
- **Celebrating cultural diversity through programming and design**

## Technology and Smart Cities

The integration of technology into urban planning offers new opportunities for community building:

### Digital Infrastructure
- **Free Wi-Fi in public spaces**
- **Digital wayfinding and information systems**
- **Online platforms for community organizing**
- **Data collection for continuous improvement**

### Responsive Design
Smart city technologies can make spaces more adaptive to community needs:
- **Lighting that responds to usage patterns**
- **Flexible infrastructure for different events**
- **Real-time feedback systems**
- **Environmental monitoring for health and comfort**

## Challenges and Opportunities

### Gentrification and Displacement
Well-designed community spaces can inadvertently contribute to gentrification. Planners must consider:
- **Affordable housing preservation**
- **Local business protection**
- **Community ownership models**
- **Equitable development strategies**

### Climate Change Adaptation
Urban planning must increasingly consider climate resilience:
- **Heat island effect mitigation**
- **Flood management and permeable surfaces**
- **Emergency shelter and evacuation routes**
- **Food security and urban agriculture**

## Case Studies in Success

### Copenhagen's Public Spaces
Copenhagen has transformed itself into one of the world's most livable cities through strategic investment in:
- **Extensive cycling infrastructure**
- **Year-round public space programming**
- **Climate-adapted design for Nordic conditions**
- **Strong public-private partnerships**

### Medell\xEDn's Urban Acupuncture
Medell\xEDn, Colombia, has used targeted architectural interventions to transform neighborhoods:
- **Library parks in underserved areas**
- **Cable car systems connecting hillside communities**
- **Green corridors along waterways**
- **Community-led improvement projects**

## The Future of Community-Centered Design

As we look toward the future, several trends are shaping community-centered urban design:

### Tactical Urbanism
Temporary, low-cost interventions that test ideas before permanent implementation:
- **Pop-up parks and parklets**
- **Temporary bike lanes**
- **Street art and murals**
- **Community gardens**

### Intergenerational Design
Spaces that bring together people of all ages:
- **Playgrounds adjacent to senior seating**
- **Community workshops and maker spaces**
- **Intergenerational housing models**
- **Shared learning environments**

## Conclusion

The future of our cities depends on our ability to create spaces that strengthen community bonds while addressing the challenges of urbanization, climate change, and social inequality. Through thoughtful urban planning and community-centered architectural design, we can build cities that are not just efficient and sustainable, but truly livable for all their inhabitants.

The most successful community spaces are those that grow and evolve with their users, adapting to changing needs while maintaining their essential character as places of gathering, exchange, and belonging. As architects and planners, our role is to provide the physical framework for community life while remaining flexible enough to support the unexpected ways that people will inhabit and transform these spaces.
    `,
    author: "Elena Nakamura",
    date: "2024-03-05",
    readTime: "10 min read",
    category: "URBAN PLANNING",
    image: urbanPlanningImg
  }
];

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List all published Nullpunkt Energy blog posts with id, title, excerpt, category, author, date, read time, and public URL. Use to answer questions about Calgary/Alberta solar incentives, engineering, and case studies.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const posts = blogPosts.map((p) => ({
      id: p.id,
      title: p.title,
      excerpt: p.excerpt,
      category: p.category,
      author: p.author,
      date: p.date,
      readTime: p.readTime,
      url: `https://nullpunkt.ca/blog/${p.id}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(posts, null, 2) }],
      structuredContent: { posts }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nullpunkt-energy-mcp",
  title: "Nullpunkt Energy MCP",
  version: "0.1.0",
  instructions: "Tools for Nullpunkt Energy (Calgary solar). Use get_solar_estimate for engineering-led PV/battery sizing and payback for Calgary/Alberta properties. Use get_services_overview for company/services/pricing context. Use list_blog_posts to surface Calgary incentive and engineering articles. Use join_waitlist to register a lead for a free consultation.",
  tools: [get_solar_estimate_default, get_services_overview_default, list_blog_posts_default, join_waitlist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
