// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-solar-estimate.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var get_solar_estimate_default = defineTool({
  name: "get_solar_estimate",
  title: "Get solar estimate",
  description: "Estimate a Calgary/Alberta solar PV system: recommended size, annual production, savings (standard vs Solar Club retailer), turn-key cost, payback, CO\u2082 avoided, and CEIP financing. Returns engineering baseline plus an AI-written recommendation.",
  inputSchema: {
    monthlyBill: z.number().positive().describe("Monthly electricity bill in CAD."),
    propertyType: z.enum(["residential", "commercial", "agricultural", "multi-family"]).describe("Property type."),
    roofOrientation: z.enum(["south", "south-east", "south-west", "east-west", "north"]).describe("Primary roof orientation."),
    roofSize: z.number().nonnegative().describe("Available roof area in m\xB2 (0 if unknown)."),
    hasEV: z.boolean().default(false).describe("Electric vehicle in the household."),
    hasBattery: z.boolean().default(false).describe("Wants battery storage."),
    postalCode: z.string().optional().describe("Canadian postal code (optional).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (input) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !anon) {
      return { content: [{ type: "text", text: "Server not configured." }], isError: true };
    }
    const res = await fetch(`${url}/functions/v1/solar-analysis`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${anon}`,
        apikey: anon
      },
      body: JSON.stringify(input)
    });
    const data = await res.json();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Solar analysis failed: ${JSON.stringify(data)}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/join-waitlist.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var join_waitlist_default = defineTool2({
  name: "join_waitlist",
  title: "Join Nullpunkt waitlist",
  description: "Register a Calgary/Alberta homeowner or business on the Nullpunkt Energy waitlist for a solar consultation. Sends confirmation and internal notification emails.",
  inputSchema: {
    name: z2.string().min(1).max(100).describe("Full name of the contact."),
    email: z2.string().email().describe("Contact email address."),
    postal_code: z2.string().max(10).optional().describe("Canadian postal code."),
    property_type: z2.string().max(50).optional().describe("e.g. residential, commercial, agricultural."),
    monthly_bill: z2.number().nonnegative().optional().describe("Monthly electricity bill in CAD."),
    notes: z2.string().max(500).optional().describe("Free-form notes from the user.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !anon) {
      return { content: [{ type: "text", text: "Server not configured." }], isError: true };
    }
    const res = await fetch(`${url}/functions/v1/join-waitlist`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${anon}`,
        apikey: anon
      },
      body: JSON.stringify({ ...input, source: "mcp" })
    });
    const data = await res.json();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Waitlist signup failed: ${JSON.stringify(data)}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `Signed up ${input.name} (${input.email}). Confirmation email sent.` }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-services-overview.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_services_overview_default = defineTool3({
  name: "get_services_overview",
  title: "Get Nullpunkt services overview",
  description: "Return a structured overview of Nullpunkt Energy's core services, target market (Calgary / Alberta), pricing posture, and contact channels.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const overview = {
      company: "Nullpunkt Energy (Calgary subsidiary of SMB Solartechnik GmbH)",
      slogan: "German Precision \u2014 Zero Emissions",
      market: "Calgary and greater Alberta, Canada",
      services: [
        {
          name: "Turn-key residential solar PV",
          description: "Engineering, permits, install, commissioning and HEMS for single-family and multi-family homes. Typical 4\u201320 kWp systems, Class 3+ hail-rated panels, 30\xB0+ tilt for winter snow shedding."
        },
        {
          name: "Commercial & agricultural solar",
          description: "150 kW\u20135 MW systems settled hourly under Alberta's Micro-Generation Regulation. Eligible for the 30% Clean Technology ITC."
        },
        {
          name: "Battery storage (LFP)",
          description: "5\u201320 kWh installed alongside PV or as retrofit; ~CAD $800/kWh turn-key."
        },
        {
          name: "Solar analysis & site design",
          description: "Free consultation, site visit, and engineering-led proposal comparing standard vs Solar Club retailer scenarios and CEIP financing."
        }
      ],
      pricing: {
        pvTurnkeyPerKwp: "CAD ~$2,100/kWp (all-in)",
        batteryPerKwh: "CAD ~$800/kWh installed",
        note: "Low end of Alberta market via direct EU supplier through SMB Solartechnik."
      },
      programs: ["Alberta Micro-Generation Regulation", "Solar Club (UTILITYnet)", "CEIP (PACE financing)", "Clean Technology ITC (30%, commercial)"],
      contact: {
        email: "hello@nullpunkt.ca",
        phone: "+1 (403) 819-7834",
        website: "https://nullpunkt.ca"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: overview
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var posts = [
  {
    id: "calgary-solar-incentives-2026",
    title: "Calgary Solar Incentives 2026: A Homeowner's Guide",
    excerpt: "What rebates, loans and net-billing programs actually pay out for a Calgary home solar system in 2026 \u2014 plus the small print most installers skip.",
    author: "NullPunkt Engineering",
    date: "2026-06-23",
    readTime: "9 min read",
    category: "INCENTIVES"
  },
  {
    id: "sustainable-architecture-future",
    title: "The Future of Sustainable Architecture",
    excerpt: "Exploring how modern architectural practices are evolving to meet environmental challenges while maintaining design excellence.",
    author: "Sarah Chen",
    date: "2024-03-15",
    readTime: "8 min read",
    category: "SUSTAINABILITY"
  },
  {
    id: "minimalism-modern-living",
    title: "Minimalism in Modern Living Spaces",
    excerpt: "How the principles of minimalist design are reshaping contemporary residential architecture and interior spaces.",
    author: "Marcus Rodriguez",
    date: "2024-03-10",
    readTime: "6 min read",
    category: "DESIGN"
  },
  {
    id: "urban-planning-community-spaces",
    title: "Urban Planning and Community Spaces",
    excerpt: "Examining the role of thoughtful urban planning in creating vibrant, inclusive communities through architectural design.",
    author: "Elena Nakamura",
    date: "2024-03-05",
    readTime: "10 min read",
    category: "URBAN PLANNING"
  }
];
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List Nullpunkt Energy blog posts with id, title, excerpt, category, author, date, read time, and public URL. Useful for Calgary/Alberta solar incentive and engineering context.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = posts.map((p) => ({ ...p, url: `https://nullpunkt.ca/blog/${p.id}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { posts: items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nullpunkt-energy-mcp",
  title: "Nullpunkt Energy MCP",
  version: "0.1.0",
  instructions: "Tools for Nullpunkt Energy (Calgary solar). Use get_solar_estimate for engineering-led PV/battery sizing and payback for Calgary/Alberta properties. Use get_services_overview for company/services/pricing context. Use list_blog_posts to surface Calgary incentive and engineering articles. Use join_waitlist to register a lead for a free consultation.",
  tools: [get_solar_estimate_default, get_services_overview_default, list_blog_posts_default, join_waitlist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
